name: Python CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  LATEST_PY: "3.14"
  LATEST_NODE: "24.x"

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false
      - name: Set up Python ${{ env.LATEST_PY }}
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
        with:
          python-version: ${{ env.LATEST_PY }}
      - name: Set up Node.js ${{ env.LATEST_NODE }}
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version: ${{ env.LATEST_NODE }}
      - name: Install dependencies
        run: |
          pip install -U .
      - name: Lint with flake8 & Prettier
        run: |
          bash scripts/lint.sh

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false
      - name: Set up Python ${{ env.LATEST_PY }}
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
        with:
          python-version: ${{ env.LATEST_PY }}
      - name: Install dependencies
        run: |
          pip install -U .
      - name: Test with pytest
        run: |
          pytest -vv
