name: Python CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  LATEST_PY: "3.14"
  LATEST_NODE: "24.x"

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Set up Python ${{ env.LATEST_PY }}
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ env.LATEST_PY }}
      - name: Set up Node.js ${{ env.LATEST_NODE }}
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: ${{ env.LATEST_NODE }}
      - name: Install dependencies
        run: |
          pip install -U .
      - name: Lint with flake8 & Prettier
        run: |
          bash scripts/lint.sh

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Set up Python ${{ env.LATEST_PY }}
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ env.LATEST_PY }}
      - name: Install dependencies
        run: |
          pip install -U .
      - name: Test with pytest
        run: |
          pytest -vv
